name: Build and Release (Code Sign Only)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for macOS
        run: npm run dist:mac -- --publish never
        env:
          CSC_LINK: ${{ secrets.SIGNING_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            release/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Get version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            ## Downloads
            See assets below for macOS builds (code signed, no notarization)
            
            Note: Users need to right-click and select "Open" on first launch.
          draft: true
          artifacts: |
            release-artifacts/mac-build/*.dmg
          token: ${{ secrets.GITHUB_TOKEN }}